services:
    shlink_web_component:
        container_name: shlink_web_component
        user: 1000:1000
        build:
            context: .
        command: /bin/sh -c "cd /shlink-web-component && npm i && npm run dev"
        volumes:
            - ./:/shlink-web-component
        ports:
            - '3002:3002'
            - '3003:3003'
